"""
Generate Snowflake DDL for TRAIN_MATRIX table from itachi_train.csv header.

Reasons for explicit DDL (not Snowsight auto-detect):
  - 5 columns have special chars (space, dot, paren) that need quoted identifiers
  - Symptom columns are 0/1 binary -> force INT (auto-detect may pick NUMBER(1,0))
  - Preserves original column names so utils/scoring.py works without changes

Usage (Windows PowerShell or sandbox):
    python scripts/generate_snowflake_ddl.py

Outputs:
    scripts/snowflake_ddl_train_matrix.sql  (paste into Snowsight worksheet)
"""
from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "data" / "raw" / "itachi_train.csv"
OUT_PATH = ROOT / "scripts" / "snowflake_ddl_train_matrix.sql"


def main() -> None:
    with CSV_PATH.open("r", encoding="utf-8") as f:
        reader = csv.reader(f)
        header = next(reader)

    assert len(header) == 133, f"Expected 133 columns, got {len(header)}"
    assert header[-1] == "prognosis", f"Last column must be 'prognosis', got {header[-1]!r}"

    symptom_cols = header[:-1]  # 132
    lines = [
        "-- Generated by scripts/generate_snowflake_ddl.py",
        "-- Source: data/raw/itachi_train.csv (5620 rows x 133 cols)",
        "-- All symptom columns are 0/1 binary -> INT",
        "-- prognosis is disease label (longest = 'Peptic ulcer diseae' ~ 30 chars) -> VARCHAR(100)",
        "-- Self-contained: idempotent (CREATE IF NOT EXISTS) — safe to re-run",
        "",
        "-- Ensure database + schema exist (no-op if already created)",
        "CREATE DATABASE IF NOT EXISTS DADS5001;",
        "CREATE SCHEMA IF NOT EXISTS DADS5001.TRIAGE;",
        "USE DATABASE DADS5001;",
        "USE SCHEMA TRIAGE;",
        "",
        "CREATE OR REPLACE TABLE TRAIN_MATRIX (",
    ]

    for col in symptom_cols:
        # Double-quote identifier to preserve case + special chars
        # Escape any inner double quotes (none expected, but defensive)
        safe = col.replace('"', '""')
        lines.append(f'    "{safe}" INT,')

    lines.append('    "prognosis" VARCHAR(100)')
    lines.append(");")
    lines.append("")
    lines.append("-- Verify table created")
    lines.append("DESC TABLE TRAIN_MATRIX;")
    lines.append("")

    sql = "\n".join(lines)
    OUT_PATH.write_text(sql, encoding="utf-8")
    print(f"OK: wrote {OUT_PATH}")
    print(f"    columns: {len(header)}")
    print(f"    file size: {OUT_PATH.stat().st_size} bytes")

    # Sanity check: count CREATE TABLE columns in output
    n_quoted = sql.count('"')
    expected = 2 * len(header)  # open + close quote per column
    assert n_quoted == expected, f"Quote count mismatch: {n_quoted} vs {expected}"
    print(f"    quoted identifiers: {n_quoted // 2} (matches header count)")


if __name__ == "__main__":
    main()
