[theme]
primaryColor = "#22B7E9"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#EEFEFF"
textColor = "#02497E"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 50
enableCORS = false

[runner]
fastReruns = true
